//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q2_ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deptdemo
    {
        public Deptdemo()
        {
            this.Empdemoes = new HashSet<Empdemo>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Empdemo> Empdemoes { get; set; }
    }
}
