//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Q2_ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empdemo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public float Salary { get; set; }
        public int DeptdemoId { get; set; }
    
        public virtual Deptdemo Deptdemo { get; set; }
    }
}
