using System;

namespace Day_10_Assignment
{
    class school
    {
        static school()
        {
             Console.WriteLine("St. Paul High School");
        }
    }

    class student : school
    {
        public static int Rollno = 0;
        public int rollnumber;
        public string name;
        public double marks;

        public student(string Name, double Marks)
        {

            this.rollnumber = ++Rollno;
            this.name = Name;
            this.marks = Marks;
        }

        public override string ToString()
        {
            return string.Format("Rollno={0}, Name={1}, Marks={2}", rollnumber, name, marks);
        }

        public void display()
        {
            Console.WriteLine(rollnumber + " " + name + " " + marks);
        }
    }
    class Q2
    {
        //Q2. Create a class school, having array of student object. 
        //    Create a class student having member variable rollnumber, name, marks .
        //    rollnumber should be generated by application.
        //    When you load application display school name. 
        //    Display all student name and marks.
        static void Main(string[] args)
        {
            school[] student = new school[3];
            student[0] = new student("tushak", 75.5);
            student[1] = new student("abhishek", 85.5);
            student[2] = new student("sahil", 80.0);


            for (int i = 0; i < 3; i++)
            {
                //Console.WriteLine(student[i].ToString());
                if(student[i] is student)
                    ((student)student[i]).display();
            }


        }
    }
}